apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudbase-serverless-postgres-depl
spec:
    selector:
        matchLabels:
            app: cloudbase-serverless-postgres-depl
    template:
        metadata:
            labels:
                app: cloudbase-serverless-postgres-depl
        spec:
            containers:
                - name: cloudbase-serverless-postgres-depl
                  image: vnavaneeth/serverless-postgres
                  #   image: postgres:10.1
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: cloudbase
                      - name: POSTGRES_USER
                        value: cloudbase
                      - name: POSTGRES_PASSWORD
                        value: cloudbase
                  resources:
                # limits:
                #   memory: '128Mi'
                #   cpu: '500m'

---
apiVersion: v1
kind: Service
metadata:
    name: cloudbase-serverless-postgres-svc
spec:
    selector:
        app: cloudbase-serverless-postgres-depl
    type: ClusterIP
    ports:
        - port: 5432
          targetPort: 5432
