# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: adapter-config
#     # namespace: monitoring
# data:
#     config.yaml: |
#         rules:
#         - seriesQuery: 'serverless_requests_total'
#           resources:
#             overrides:
#               kubernetes_namespace:
#                 resource: namespace
#               kubernetes_pod_name:
#                 resource: pod
#           name:
#             matches: "^(.*)_total"
#             as: "${1}_per_second"
#           metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))
